package codex

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strings"
	"testing"

	"github.com/charmbracelet/log"

	"github.com/evanmschultz/valv/internal/adapters/docker"
	"github.com/evanmschultz/valv/internal/domain"
	projectdetect "github.com/evanmschultz/valv/internal/project"
)

type fakeStore struct {
	project     domain.Project
	projectErr  error
	binding     domain.ProjectBinding
	bindingErr  error
	profile     domain.Profile
	profileErr  error
	projectRoot string
	profileID   string
}

func (f fakeStore) CreateProject(context.Context, domain.Project) (domain.Project, error) {
	panic("unexpected call")
}

func (f fakeStore) ProjectByRoot(_ context.Context, root string) (domain.Project, error) {
	f.projectRoot = root
	return f.project, f.projectErr
}

func (f fakeStore) CreateProfile(context.Context, domain.Profile) (domain.Profile, error) {
	panic("unexpected call")
}

func (f fakeStore) ProfileByID(_ context.Context, id string) (domain.Profile, error) {
	f.profileID = id
	return f.profile, f.profileErr
}

func (f fakeStore) ProfileByName(context.Context, domain.Provider, string) (domain.Profile, error) {
	panic("unexpected call")
}

func (f fakeStore) UpsertProjectBinding(context.Context, domain.ProjectBinding) (domain.ProjectBinding, error) {
	panic("unexpected call")
}

func (f fakeStore) BindingByProjectID(context.Context, string) (domain.ProjectBinding, error) {
	return f.binding, f.bindingErr
}

type fakeExecutor struct {
	got docker.ContainerRunRequest
	err error
}

func (f *fakeExecutor) Run(_ context.Context, request docker.ContainerRunRequest) error {
	f.got = request
	return f.err
}

func TestNewRequiresDependencies(t *testing.T) {
	t.Parallel()

	_, err := New(Options{})
	if err == nil {
		t.Fatal("New() error = nil, want dependency failure")
	}
}

func TestRunReturnsUnboundProjectWhenProjectMissing(t *testing.T) {
	t.Parallel()

	executor := &fakeExecutor{}
	service, err := New(Options{
		Store: fakeStore{
			projectErr: fmt.Errorf("missing project: %w", domain.ErrNotFound),
		},
		Executor: executor,
		Detect: func(start string) (projectdetect.Result, error) {
			return projectdetect.Result{Root: start}, nil
		},
		Image: docker.NewImageRef("valv-codex", "dev"),
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = service.Run(context.Background(), "/tmp/project", []string{"resume", "abc"})
	if !errors.Is(err, domain.ErrUnboundProject) {
		t.Fatalf("Run() error = %v, want domain.ErrUnboundProject", err)
	}
}

func TestRunBuildsDockerRequestFromProjectBindingAndProfile(t *testing.T) {
	t.Parallel()

	project := domain.Project{ID: "project-1234567890", Root: "/tmp/project", Name: "project"}
	binding := domain.ProjectBinding{ProjectID: project.ID, ProfileID: "profile-1", Provider: domain.ProviderCodex}
	profile := domain.Profile{ID: "profile-1", Provider: domain.ProviderCodex, Name: "dev", HomePath: "/tmp/valv/providers/codex/profiles/dev"}
	executor := &fakeExecutor{}
	service, err := New(Options{
		Store: fakeStore{
			project: project,
			binding: binding,
			profile: profile,
		},
		Executor: executor,
		Detect: func(start string) (projectdetect.Result, error) {
			return projectdetect.Result{Root: project.Root, HasGitMarker: true}, nil
		},
		Image:  docker.NewImageRef("valv-codex", "dev"),
		User:   "501:20",
		TTY:    true,
		Stdin:  true,
		Logger: log.NewWithOptions(io.Discard, log.Options{Level: log.DebugLevel}),
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	args := []string{"resume", "session-123", "--model", "gpt-5-codex"}
	if err := service.Run(context.Background(), "/tmp/project/subdir", args); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	if executor.got.Name != "" {
		t.Fatalf("Run() container name = %q, want empty autogenerated name", executor.got.Name)
	}
	if executor.got.WorkingDir != "/tmp/project/subdir" {
		t.Fatalf("Run() working dir = %q", executor.got.WorkingDir)
	}
	if executor.got.Image.String() != "valv-codex:dev" {
		t.Fatalf("Run() image = %q", executor.got.Image.String())
	}
	if executor.got.User != "501:20" {
		t.Fatalf("Run() user = %q", executor.got.User)
	}
	if !executor.got.Interactive || !executor.got.TTY || !executor.got.Remove {
		t.Fatalf("Run() interactive flags = %+v", executor.got)
	}
	if got := executor.got.Env["CODEX_HOME"]; got != profile.HomePath {
		t.Fatalf("Run() CODEX_HOME = %q, want %q", got, profile.HomePath)
	}
	if len(executor.got.Mounts) != 2 {
		t.Fatalf("Run() mounts len = %d, want 2", len(executor.got.Mounts))
	}
	if executor.got.Mounts[0] != docker.NewMountSpec(project.Root, project.Root, false) {
		t.Fatalf("Run() project mount = %+v", executor.got.Mounts[0])
	}
	if executor.got.Mounts[1] != docker.NewMountSpec(profile.HomePath, profile.HomePath, false) {
		t.Fatalf("Run() profile mount = %+v", executor.got.Mounts[1])
	}
	for index, arg := range args {
		if executor.got.Args[index] != arg {
			t.Fatalf("Run() args[%d] = %q, want %q", index, executor.got.Args[index], arg)
		}
	}
}

func TestRunBubblesExecutorErrors(t *testing.T) {
	t.Parallel()

	project := domain.Project{ID: "project-1234567890", Root: "/tmp/project", Name: "project"}
	executor := &fakeExecutor{err: errors.New("docker failed")}
	service, err := New(Options{
		Store: fakeStore{
			project: project,
			binding: domain.ProjectBinding{ProjectID: project.ID, ProfileID: "profile-1", Provider: domain.ProviderCodex},
			profile: domain.Profile{ID: "profile-1", Provider: domain.ProviderCodex, HomePath: "/tmp/profile"},
		},
		Executor: executor,
		Detect: func(start string) (projectdetect.Result, error) {
			return projectdetect.Result{Root: project.Root}, nil
		},
		Image: docker.NewImageRef("valv-codex", "dev"),
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = service.Run(context.Background(), "/tmp/project", []string{"resume", "abc"})
	if err == nil || !strings.Contains(err.Error(), "docker failed") {
		t.Fatalf("Run() error = %v, want wrapped docker error", err)
	}
}

func TestRunBuildsNonInteractiveDockerRequestWhenTTYDisabled(t *testing.T) {
	t.Parallel()

	project := domain.Project{ID: "project-1234567890", Root: "/tmp/project", Name: "project"}
	executor := &fakeExecutor{}
	service, err := New(Options{
		Store: fakeStore{
			project: project,
			binding: domain.ProjectBinding{ProjectID: project.ID, ProfileID: "profile-1", Provider: domain.ProviderCodex},
			profile: domain.Profile{ID: "profile-1", Provider: domain.ProviderCodex, HomePath: "/tmp/profile"},
		},
		Executor: executor,
		Detect: func(start string) (projectdetect.Result, error) {
			return projectdetect.Result{Root: project.Root}, nil
		},
		Image: docker.NewImageRef("valv-codex", "dev"),
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	if err := service.Run(context.Background(), "/tmp/project", []string{"exec", "status"}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if executor.got.Interactive || executor.got.TTY {
		t.Fatalf("Run() interactive flags = %+v, want non-interactive request", executor.got)
	}
}

func TestRunRejectsWorkingDirectoryOutsideProjectRoot(t *testing.T) {
	t.Parallel()

	project := domain.Project{ID: "project-1234567890", Root: "/tmp/project", Name: "project"}
	service, err := New(Options{
		Store: fakeStore{
			project: project,
			binding: domain.ProjectBinding{ProjectID: project.ID, ProfileID: "profile-1", Provider: domain.ProviderCodex},
			profile: domain.Profile{ID: "profile-1", Provider: domain.ProviderCodex, HomePath: "/tmp/profile"},
		},
		Executor: &fakeExecutor{},
		Detect: func(start string) (projectdetect.Result, error) {
			return projectdetect.Result{Root: project.Root}, nil
		},
		Image: docker.NewImageRef("valv-codex", "dev"),
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = service.Run(context.Background(), "/tmp/other", []string{"resume", "abc"})
	if err == nil || !strings.Contains(err.Error(), "outside project root") {
		t.Fatalf("Run() error = %v, want working dir validation", err)
	}
}

func TestRunRejectsSiblingPathThatSharesProjectPrefix(t *testing.T) {
	t.Parallel()

	project := domain.Project{ID: "project-1234567890", Root: "/tmp/project", Name: "project"}
	service, err := New(Options{
		Store: fakeStore{
			project: project,
			binding: domain.ProjectBinding{ProjectID: project.ID, ProfileID: "profile-1", Provider: domain.ProviderCodex},
			profile: domain.Profile{ID: "profile-1", Provider: domain.ProviderCodex, HomePath: "/tmp/profile"},
		},
		Executor: &fakeExecutor{},
		Detect: func(start string) (projectdetect.Result, error) {
			return projectdetect.Result{Root: project.Root}, nil
		},
		Image: docker.NewImageRef("valv-codex", "dev"),
	})
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	err = service.Run(context.Background(), "/tmp/project2", []string{"resume", "abc"})
	if err == nil || !strings.Contains(err.Error(), "outside project root") {
		t.Fatalf("Run() error = %v, want sibling path rejection", err)
	}
}
